package protocol;

public enum MessageType {
    REGISTER_REQUEST, REGISTER_RESULT, LOGIN_REQUEST, LOGIN_RESULT, LOGOUT_REQUEST, LOGOUT_RESULT, ONLINE_LIST, INVITE_REQUEST, INVITE_RECEIVED, INVITE_ACCEPT, INVITE_REJECT, INVITE_RESULT, CREATE_BOT_MATCH, MATCH_STARTED, TURN_PREPARING, ROTATION_SUBMIT, ROTATION_APPLIED, TURN_STARTED, THROW_COORDINATE, THROW_RESOLVED, MATCH_FINISHED, CHAT_MESSAGE, LEAVE_MATCH, GET_RANKING, RANKING_RESULT, GET_HISTORY, HISTORY_RESULT, ERROR
}
